# 2019-05-28-домашняя работа

## Задание 1

In [1]:
import numpy as np

In [31]:
x = np.arange(10, 0, -1)

In [32]:
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [36]:
N = 10
step = -1
np.arange(N - 1, -1, step)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## Задание 2

In [53]:
def diag_mat(N):
    diag_mat=np.diag(np.arange(N-1, -1, -1), k=0)
    return diag_mat

In [54]:
X=diag_mat(15)

In [55]:
X

array([[14,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 13,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 12,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 11,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  9,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  8,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  7,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  5,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  4,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  3,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0

In [49]:
np.sum(X)

105

In [50]:
def diag_mat_sum(N):
    return np.sum(diag_mat(N))

In [51]:
N=5
diag_mat_sum(N)

10

## Задание 3

In [131]:
movies = pd.read_csv('./ml-latest-small/movies.csv')

In [132]:
movies.head()

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy

In [133]:
ratings = pd.read_csv('./ml-latest-small/ratings.csv')

In [134]:
ratings.head()

userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [135]:
joined = ratings.merge(movies, on='movieId', how='left')
joined.head()

userId  movieId  rating  timestamp                        title  \
0       1        1     4.0  964982703             Toy Story (1995)   
1       1        3     4.0  964981247      Grumpier Old Men (1995)   
2       1        6     4.0  964982224                  Heat (1995)   
3       1       47     5.0  964983815  Seven (a.k.a. Se7en) (1995)   
4       1       50     5.0  964982931   Usual Suspects, The (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                               Comedy|Romance  
2                        Action|Crime|Thriller  
3                             Mystery|Thriller  
4                       Crime|Mystery|Thriller

In [137]:
joined['rating'].value_counts()

4.0    26818
3.0    20047
5.0    13211
3.5    13136
4.5     8551
2.0     7551
2.5     5550
1.0     2811
1.5     1791
0.5     1370
Name: rating, dtype: int64

In [138]:
filtered_rating = joined[(joined['rating'] == 5.0)]

In [139]:
filtered_rating.head() 

userId  movieId  rating  timestamp                        title  \
3       1       47     5.0  964983815  Seven (a.k.a. Se7en) (1995)   
4       1       50     5.0  964982931   Usual Suspects, The (1995)   
6       1      101     5.0  964980868         Bottle Rocket (1996)   
8       1      151     5.0  964984041               Rob Roy (1995)   
9       1      157     5.0  964984100        Canadian Bacon (1995)   

                           genres  
3                Mystery|Thriller  
4          Crime|Mystery|Thriller  
6  Adventure|Comedy|Crime|Romance  
8        Action|Drama|Romance|War  
9                      Comedy|War

In [146]:
filtered_rating['title'].value_counts()[:1]

Shawshank Redemption, The (1994)    153
Name: title, dtype: int64

## Задание 4

In [70]:
import pandas as pd

In [72]:
data = pd.read_csv('./Python_5_pandas/power.csv')

In [73]:
data.head()

country  year  quantity  category
0  Austria  1996       5.0         1
1  Austria  1995      17.0         1
2  Belgium  2014       0.0         1
3  Belgium  2013       0.0         1
4  Belgium  2012      35.0         1

In [74]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1189482 entries, 0 to 1189481
Data columns (total 4 columns):
country     1189482 non-null object
year        1189482 non-null int64
quantity    1189482 non-null float64
category    1189482 non-null int64
dtypes: float64(1), int64(2), object(1)
memory usage: 36.3+ MB


In [75]:
data.describe()

year      quantity      category
count  1.189482e+06  1.189482e+06  1.189482e+06
mean   2.002852e+03  1.842648e+05  3.624763e+01
std    7.167345e+00  1.585663e+07  1.809968e+01
min    1.990000e+03 -8.643480e+05  1.000000e+00
25%    1.997000e+03  1.400000e+01  2.400000e+01
50%    2.003000e+03  1.890000e+02  3.500000e+01
75%    2.009000e+03  2.265000e+03  5.100000e+01
max    2.014000e+03  6.680329e+09  7.100000e+01

In [83]:
# Ищем, как пишется Литва

data[data['country'].str.contains('Li', case=False)] ['country'].unique()

array(['Korea, Republic of', 'Lithuania', 'Australia', 'Philippines',
       'Republic of Moldova', 'Belize', 'Bolivia (Plur. State of)',
       'Dominican Republic', 'Liberia', 'Libya',
       'Venezuela (Bolivar. Rep.)', 'Mali', 'Syrian Arab Republic',
       'Somalia', 'Mongolia', 'Liechtenstein', 'Wallis and Futuna Is.'], dtype=object)

In [126]:
# Ищем Латвию
data[data['country'].str.contains('Lat', case=False)] ['country'].unique()

array(['Latvia'], dtype=object)

In [127]:
# Ищем Эстонию
data[data['country'].str.contains('Es', case=False)] ['country'].unique()

array(['United States', 'Philippines', 'Bangladesh', 'Lesotho',
       'United Arab Emirates', 'Estonia', 'Indonesia', 'Maldives',
       'Seychelles', 'Neth. Antilles (former)', 'French Polynesia',
       'St. Vincent-Grenadines', 'State of Palestine',
       'Micronesia (Fed. States of)', 'Timor-Leste',
       'United States Virgin Is.',
       'Commonwealth of Independent States (CIS)', 'Antarctic Fisheries'], dtype=object)

In [128]:
filtered_countries = data[((data['country'] == 'Latvia') | 
                          (data['country'] == 'Lithuania') | 
                          (data['country'] == 'Estonia')) & 
                          ((data['year'] >= 2005) & (data['year'] <= 2010)) &
                          ((data['category'] == 4) | (data['category'] == 12) | (data['category'] == 21)) &
                          (data['quantity']>= 0)                    
                         ]

In [129]:
filtered_countries.head()

country  year  quantity  category
10617    Estonia  2008       1.0         4
10618    Estonia  2007       0.0         4
10619    Estonia  2006       0.0         4
10620    Estonia  2005       1.0         4
11156  Lithuania  2008       1.0         4

In [130]:
filtered_countries.shape

(408, 4)

In [120]:
sum(filtered_countries ['quantity'])

240580.0

In [121]:
filtered_countries ['quantity'].sum()

240580.0

## Задание 5

In [63]:
a=np.array([ [4, 1, 0], [2, 3, 5], [1, 0, 4]] )

In [64]:
b=np.array( [4, 12, -3] )

In [65]:
from numpy import linalg

In [66]:
linalg.solve(a,b)

array([-0.33333333,  5.33333333, -0.66666667])

In [67]:
np.allclose( np.dot(a, linalg.solve(a,b)), b)

True